version: '3.8'
    
services:
  analyzer:
    environment:
      - PASSWORD_KARAFKA=${PASSWORD_KARAFKA}
      - USERNAME_KARAFKA=${USERNAME_KARAFKA}
    build: logs-analyzer
  programmer-email-provider:
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - EUREKA_SERVER=${EUREKA_SERVER}
      - PORT=0
    build: logs-bugs-email-provider
  assigner-email-provider:
    environment:
      - EUREKA_SERVER=${EUREKA_SERVER}
      - PORT=0
    build: logs-bugs-assigner-mail-provider
  email-notifier:
    environment:
      - PASSWORD_KARAFKA=${PASSWORD_KARAFKA}
      - USERNAME_KARAFKA=${USERNAME_KARAFKA}
      - GMAIL_PASSWORD=${GMAIL_PASSWORd}
      - GMAIL_USERNAME=${GMAIL_USERNAME}
      - EUREKA_SERVER=${EUREKA_SERVER}
    build: logs-bugs-email-notifier
  bugs-opening:
    environment:
      - PASSWORD_KARAFKA=${PASSWORD_KARAFKA}
      - USERNAME_KARAFKA=${USERNAME_KARAFKA}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build: logs-bugs-opening
  reporter-back-office:
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build: logs-bugs-reporter-back-office
  db-populator:
    environment:
      - PASSWORD_KARAFKA=${PASSWORD_KARAFKA}
      - USERNAME_KARAFKA=${USERNAME_KARAFKA}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    build: logs-db-populator
  logs-info-back-office:
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    build: logs-info-back-office
  discovery-server:
    ports:
      - 8761:8761
    build: logs-bugs-discovery-server
  accounts-provider:
    environment:
      - PORT=0
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - EUREKA_SERVER=${EUREKA_SERVER}
    build: logs-bugs-accounts-provider
  gateway:
    ports:
      - 9191:9191
    environment:
      - EUREKA_SERVER=${EUREKA_SERVER}
      - SPRING_PROFILES_ACTIVE=docker
    build: logs-bugs-gateway    