DROP TABLE bugs;
create table bugs (id bigint generated by default as identity, date_close date, date_open date not null, description varchar(255) not null, openning_method varchar(255) not null, seriousness varchar(255) not null, status varchar(255) not null, programmer_id bigint, primary key (id));
delete from artifacts;
delete from programmer;